# Generated by Django 5.1.5 on 2025-01-23 21:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterUserModel',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pages.basemodel')),
                ('name', models.CharField(max_length=128)),
            ],
            bases=('pages.basemodel',),
        ),
    ]
